default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: <%= ENV['LEATHER_APP_DATABASE_USERNAME'] %>
  password: <%= ENV['LEATHER_APP_DATABASE_PASSWORD'] %>
  host: <%= ENV['LEATHER_APP_DATABASE_HOST'] %>
development:
  <<: *default
  database: leather_app_development
test:
  <<: *default
  database: leather_app_test
production:
  <<: *default
  database: leather_app_production
